apps/crud/models.py
from datetime import datetime

from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

# User 클래스를 db.Model에 더해서 UserMixin을 상속한다
class User(db.Model, UserMixin):
    # 테이블명을 지정한다
    __tablename__ = "users"

    # 컬럼을 정의한다
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(
        db.DateTime, default=datetime.now, onupdate=datetime.now
    )

    # 비밀번호를 설정하기 위한 프로퍼티
    @property
    def password(self):
        raise AttributeError("읽어 들일 수 없음")

    # 비밀번호를 설정하기 위해 setter 함수로 해시화한 비밀번호를 설정한다
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 비밀번호 체크를 한다
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    # 이메일 주소 중복 체크를 한다
    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None
    
# 로그인하고 있는 사용자 정보를 취득하는 함수를 작성한다
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, Length

# 사용자 신규 작성과 사용자 편집 폼 클래스
class UserForm(FlaskForm):
    # 사용자 폼의 username 속성의 라벨과 검증을 설정한다
    username = StringField(
        "사용자명",
        validators=[
            DataRequired(message="사용자명은 필수입니다. "),
            Length(max=30, message="30문자 이내로 입력해 주세요. "),
        ],
    )

    # 사용자폼 email 속성의 라벨과 검증을 설정한다
    email = StringField(
        "메일주소",
        validators=[
            DataRequired(message="메일 주소는 필수입니다. "),
            Email(message="메일 주소의 형식으로 입력해 주세요. "),
        ],
    )

    # 사용자폼 password 속성의 라벨과 검증을 설정한다
    password = PasswordField(
        "비밀번호",
        validators=[DataRequired(message="비밀번호는 필수입니다. ")]
    )

    # 사용자폼 submit의 문구를 설정한다
    submit = SubmitField("신규 등록")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
# db를 import한다
from apps.app import db
# User 클래스를 import 한다
from apps.crud.models import User

from apps.crud.forms import UserForm
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

# Blueprint로 crud 앱을 생성한다
crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)

# index 엔드포인트를 작성하고 index.html을 반환한다
@crud.route("/")
# 데코레이터를 추가한다
@login_required
def index():
    return render_template("crud/index.html")

# 모든 엔드포인트에 @login_required를 추가한다
@crud.route('/sql')
@login_required
def sql():
    # 사용자 모델 객체를 작성한다
    '''
    user = User(
        username="김성진",
        email="oksjjj@gmail.com",
        password="char1014"
    )
    '''

    # 사용자를 추가한다
    #db.session.add(user)
    user = db.session.query(User).filter_by(id=1).delete()

    # 커밋한다
    db.session.commit()

    return "콘솔 로그를 확인해 주세요"

@crud.route("/users/new", methods=["GET", "POST"])
@login_required
def create_user():
    # UserForms을 인스턴스화한다
    form = UserForm()
    # 폼의 값을 검증한다
    if form.validate_on_submit():
        # 사용자를 작성한다
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        # 사용자를 추가하고 커밋한다
        db.session.add(user)
        db.session.commit()
        # 사용자의 알람 화면으로 리다이렉트한다
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)

@crud.route("/users")
@login_required
def users():
    """사용자의 알람을 취득한다"""
    users = User.query.all()
    return render_template("crud/index.html", users=users)

# methods에 GET과 POST를 지정한다
@crud.route("/users/<user_id>", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    form = UserForm()

    # User 모델을 이용하여 사용자를 취득한다
    user = User.query.filter_by(id=user_id).first()

    # form으로부터 제출된 경우는 사용자를 갱신하여 사용자의 일람 화면으로 리다이렉트한다
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    
    # GET의 경우는 HTML을 반환한다
    return render_template("crud/edit.html", user=user, form=form)

@crud.route("/users/<user_id>/delete", methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <!-- title을 상속처에서 구현한다 -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}" />
</head>
<body>
    <div>
        {% if current_user.is_authenticated %}
        <p>
            <span>{{ current_user.username }}</span> -
            <span><a href="{{ url_for('auth.logout') }}">로그아웃</a></span>
        </p>
        {% endif %}
    </div>
    <!-- content를 상속처에서 구현한다 -->
    {% block content %}{% endblock %}
</body>
</html>

apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}사용자 신규 작성{% endblock %}
{% block content %}

<h2>사용자 신규 작성</h2>
<form
    action="{{ url_for('crud.create_user') }}"
    method="POST"
    novalidate="novalidate"
>
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="사용자명") }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.email.label }} {{ form.email(placeholder="메일 주소") }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }} {{ form.password(placeholder="비밀번호") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends 'crud/base.html' %}
{% block title %}사용자 편집{% endblock %}
{% block content %}

<h2>사용자 편집</h2>

<form
    action="{{ url_for('crud.edit_user', user_id=user.id) }}"
    method="POST"
    novalidate="novalidate"
>
    {{ form.csrf_token }}
    <p>
        {{ form.username.label }} {{ form.username(placeholder="사용자명", value=user.username) }}
    </p>
    {% for error in form.username.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.email.label }} {{ form.email(placeholder="메일 주소", value=user.email) }}
    </p>
    {% for error in form.email.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label }} {{ form.password(placeholder="비밀번호") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p><input type="submit" value="갱신"></p>
</form>

<form action="{{ url_for('crud.delete_user', user_id=user.id )}}" method="POST">
    {{ form.csrf_token }}
    <input type="submit" value="삭제">
</form>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %}사용자의 일람{% endblock %}
{% block content %}
<h2>사용자의 일람</h2>

<a href="{{ url_for('crud.create_user') }}">사용자 신규 작성</a>

<table>
    <tr>
        <th>사용자 ID</th>
        <th>사용자명</th>
        <th>메일 주소</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>
            <a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a>    
        </td>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}